// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwu8IE-gKEr6uP7378f6dsNnw14-p-Qw',
    appId: '1:454209738650:web:110c28c6e0a2be6326cc23',
    messagingSenderId: '454209738650',
    projectId: 'garma-garam-tiffin-app',
    authDomain: 'garma-garam-tiffin-app.firebaseapp.com',
    storageBucket: 'garma-garam-tiffin-app.appspot.com',
    measurementId: 'G-1TJYVWDRG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ14IDTtJyv2xFX80Mo0GK-W8pUAGScV8',
    appId: '1:454209738650:android:13d9d6448b52a6c926cc23',
    messagingSenderId: '454209738650',
    projectId: 'garma-garam-tiffin-app',
    storageBucket: 'garma-garam-tiffin-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwu8IE-gKEr6uP7378f6dsNnw14-p-Qw',
    appId: '1:454209738650:web:5f61539dbbea6ec026cc23',
    messagingSenderId: '454209738650',
    projectId: 'garma-garam-tiffin-app',
    authDomain: 'garma-garam-tiffin-app.firebaseapp.com',
    storageBucket: 'garma-garam-tiffin-app.appspot.com',
    measurementId: 'G-7JKYCRCTG7',
  );
}
